import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Download, FileText, LoaderCircle, Pencil, RefreshCw, X } from "lucide-react";
import { ErrorState, LoadingSkeleton } from "../../components/ui/States";
import { cx, formatDateTime, formatSpeed } from "../../lib/format";
import { api } from "../../services/api";
import type { ReportRecord } from "../../types";
import { reportStatusTone, reportTypeLabel, sectionLabel } from "./reportFormat";

function duration(seconds: number | null | undefined) {
  if (seconds == null) return "Not measured";
  if (seconds < 60) return `${Math.round(seconds)} seconds`;
  if (seconds < 3600) return `${Math.round(seconds / 60)} minutes`;
  return `${(seconds / 3600).toFixed(1)} hours`;
}

export function ReportPreviewDrawer({ report, onClose, onRegenerated }: {
  report: ReportRecord | null;
  onClose: () => void;
  onRegenerated: (report: ReportRecord) => void;
}) {
  const close = useRef<HTMLButtonElement>(null);
  const client = useQueryClient();
  const [renaming, setRenaming] = useState(false);
  const [name, setName] = useState(report?.name ?? "");
  const detail = useQuery({ queryKey: ["reports", "detail", report?.id], queryFn: () => api.getReport(report!.id), enabled: Boolean(report), placeholderData: report ?? undefined });
  const rename = useMutation({ mutationFn: () => api.renameReport(report!.id, name.trim()), onSuccess: (updated) => { client.setQueryData(["reports", "detail", updated.id], updated); void client.invalidateQueries({ queryKey: ["reports"] }); setRenaming(false); } });
  const regenerate = useMutation({ mutationFn: () => api.regenerateReport(report!.id), onSuccess: (updated) => { void client.invalidateQueries({ queryKey: ["reports"] }); void client.invalidateQueries({ queryKey: ["reports-summary"] }); onRegenerated(updated); } });
  useEffect(() => {
    if (!report) return;
    close.current?.focus();
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    document.addEventListener("keydown", escape);
    return () => document.removeEventListener("keydown", escape);
  }, [report, onClose]);
  if (!report) return null;
  const current = detail.data;
  const snapshot = current?.snapshot;
  const status = current?.status ?? report.status;
  return <div className="fixed inset-0 z-[70] bg-black/65" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside role="dialog" aria-modal="true" aria-labelledby="report-preview-title" className="ml-auto flex h-full w-full max-w-3xl flex-col border-l border-border bg-surface shadow-2xl"><header className="flex items-start justify-between gap-4 border-b border-border p-4"><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Report #{report.id} · Version {report.version}</p>{renaming ? <div className="mt-2 flex gap-2"><input autoFocus value={name} maxLength={120} onChange={(event) => setName(event.target.value)} className="field" aria-label="New report name" /><button disabled={name.trim().length < 2 || rename.isPending} onClick={() => rename.mutate()} className="primary-button h-11">Save</button><button onClick={() => { setName(current?.name ?? report.name); setRenaming(false); }} className="secondary-button h-11">Cancel</button></div> : <h2 id="report-preview-title" className="mt-1 truncate text-lg font-bold">{current?.name ?? report.name}</h2>}<div className="mt-2 flex flex-wrap items-center gap-2"><span className={cx("rounded-lg px-2 py-1 text-[9px] font-bold uppercase", reportStatusTone(status))}>{status}</span><span className="text-xs text-muted">{reportTypeLabel(current?.type ?? report.type)}</span></div></div><button ref={close} onClick={onClose} className="icon-button" aria-label="Close report preview"><X size={18} /></button></header><div className="scrollbar-thin flex-1 overflow-y-auto p-4 sm:p-5">{detail.isLoading && <LoadingSkeleton className="h-96" />}{detail.isError && <ErrorState message="Report details could not be loaded." />}{current && <>
        <div className="mb-4 flex flex-wrap gap-2"><button type="button" onClick={() => setRenaming(true)} className="secondary-button"><Pencil size={14} />Rename</button><button type="button" disabled={regenerate.isPending} onClick={() => regenerate.mutate()} className="secondary-button"><RefreshCw className={regenerate.isPending ? "animate-spin" : ""} size={14} />Regenerate</button>{current.availableFormats.includes("pdf") && <a href={api.getReportDownloadUrl(current.id, "pdf")} className="primary-button h-10"><Download size={14} />PDF</a>}{current.availableFormats.includes("csv") && <a href={api.getReportDownloadUrl(current.id, "csv")} className="secondary-button"><Download size={14} />CSV</a>}</div>
        {regenerate.error && <p role="alert" className="mb-4 rounded-xl bg-danger/10 p-3 text-xs text-danger">{regenerate.error.message}</p>}
        {status === "GENERATING" && <div className="grid min-h-48 place-items-center rounded-xl border border-border bg-card text-center"><div><LoaderCircle className="mx-auto animate-spin text-warning" /><strong className="mt-3 block">Report is generating</strong><p className="mt-1 text-xs text-muted">Exports will become available when generation finishes.</p></div></div>}
        {status === "FAILED" && <div className="rounded-xl border border-danger/20 bg-danger/5 p-4"><strong className="flex items-center gap-2 text-danger"><AlertTriangle size={16} />Report generation failed</strong><p className="mt-2 text-xs text-muted">{current.failureReason || "No safe failure detail is available."}</p></div>}
        {status === "READY" && snapshot && <>
          <section className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="metric-label">Generated from confirmed recorded events</p><h3 className="mt-1 text-lg font-bold">{reportTypeLabel(snapshot.reportType)}</h3></div><FileText className="text-primary" /></div><dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><div><dt className="text-muted">Reporting period</dt><dd className="mt-1 font-semibold tabular-nums">{formatDateTime(snapshot.filters.startAt)} – {formatDateTime(snapshot.filters.endAt)}</dd></div><div><dt className="text-muted">Timezone</dt><dd className="mt-1 font-semibold">{snapshot.timezone}</dd></div><div><dt className="text-muted">Camera</dt><dd className="mt-1 font-semibold">{snapshot.camera.cameraName}</dd></div><div><dt className="text-muted">Generated</dt><dd className="mt-1 font-semibold tabular-nums">{formatDateTime(snapshot.generatedAt)}</dd></div></dl></section>
          <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Report source counts">{Object.entries(snapshot.sourceCounts).map(([label, value]) => <article key={label} className="rounded-xl border border-border bg-card p-3"><p className="metric-label">{label.replaceAll(/([A-Z])/g, " $1")}</p><strong className="metric-small">{value.toLocaleString()}</strong></article>)}</section>
          <section className="mt-4 grid gap-3 sm:grid-cols-2"><article className="rounded-xl border border-border bg-card p-4"><p className="metric-label">Average measured speed</p><strong className="metric-small">{snapshot.traffic.averageSpeed == null ? "Not measured" : `${formatSpeed(snapshot.traffic.averageSpeed)} km/h`}</strong><p className="metric-note">{snapshot.traffic.measuredSpeedCount.toLocaleString()} measured records</p></article><article className="rounded-xl border border-border bg-card p-4"><p className="metric-label">Maximum measured speed</p><strong className="metric-small">{snapshot.traffic.maximumSpeed == null ? "Not measured" : `${formatSpeed(snapshot.traffic.maximumSpeed)} km/h`}</strong><p className="metric-note">Missing speed is never treated as zero</p></article><article className="rounded-xl border border-border bg-card p-4"><p className="metric-label">Average acknowledgement</p><strong className="metric-small">{duration(snapshot.alerts.averageAcknowledgementSeconds)}</strong></article><article className="rounded-xl border border-border bg-card p-4"><p className="metric-label">Average resolution</p><strong className="metric-small">{duration(snapshot.alerts.averageResolutionSeconds)}</strong></article></section>
          {snapshot.warnings.length > 0 && <aside className="mt-4 rounded-xl border border-warning/20 bg-warning/5 p-4"><strong className="flex items-center gap-2 text-xs text-warning"><AlertTriangle size={14} />Configuration and availability notes</strong><ul className="mt-2 space-y-1 text-xs text-muted">{snapshot.warnings.map((warning) => <li key={warning}>• {warning}</li>)}</ul></aside>}
          <section className="mt-4 rounded-xl border border-border bg-card p-4"><h3 className="text-xs font-bold uppercase tracking-wider">Included sections</h3><div className="mt-3 flex flex-wrap gap-2">{snapshot.sections.map((section) => <span key={section} className="rounded-lg bg-elevated px-2.5 py-1 text-[10px]">{sectionLabel(section)}</span>)}</div><p className="mt-4 text-xs text-muted">{snapshot.dataNote}</p></section>
          {snapshot.traffic.trafficTrend.length > 0 ? <section className="mt-4 overflow-hidden rounded-xl border border-border bg-card"><header className="border-b border-border p-3 text-xs font-bold uppercase tracking-wider">Traffic trend</header><div className="max-h-64 overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-surface-secondary text-muted"><tr><th className="p-3">Period</th><th className="p-3">Detections</th><th className="p-3">Overspeed</th></tr></thead><tbody className="divide-y divide-border">{snapshot.traffic.trafficTrend.map((item) => <tr key={item.period}><td className="p-3 tabular-nums">{formatDateTime(item.period)}</td><td className="p-3 tabular-nums">{item.detections}</td><td className="p-3 tabular-nums text-danger">{item.overspeed}</td></tr>)}</tbody></table></div></section> : <section className="mt-4 rounded-xl border border-border bg-card p-8 text-center"><strong>No matching source records</strong><p className="mt-1 text-xs text-muted">This is a valid zero-result report; no sample rows were inserted.</p></section>}
          {snapshot.sections.includes("violationRecords") && snapshot.violations.records.length > 0 && <section className="mt-4 overflow-hidden rounded-xl border border-border bg-card"><header className="border-b border-border p-3 text-xs font-bold uppercase tracking-wider">Confirmed violation records</header><div className="max-h-72 overflow-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="sticky top-0 bg-surface-secondary text-muted"><tr><th className="p-3">Event</th><th className="p-3">Violation</th><th className="p-3">Vehicle / tracking</th><th className="p-3">Speed</th><th className="p-3">Camera</th><th className="p-3">Detected</th></tr></thead><tbody className="divide-y divide-border">{snapshot.violations.records.slice(0, 200).map((item) => <tr key={String(item.id)}><td className="p-3 text-primary">#{String(item.id)}</td><td className="p-3">{String(item.type).replaceAll("_", " ")}</td><td className="p-3">{String(item.plate || `Track #${String(item.trackingId)}`)}</td><td className="p-3">{item.speed == null ? "Not measured" : `${String(item.speed)} / ${String(item.speedLimit)} km/h`}</td><td className="p-3">{String(item.cameraId)}</td><td className="p-3 tabular-nums">{formatDateTime(String(item.detectedAt))}</td></tr>)}</tbody></table></div></section>}
          {snapshot.sections.includes("alertRecords") && snapshot.alerts.records.length > 0 && <section className="mt-4 overflow-hidden rounded-xl border border-border bg-card"><header className="border-b border-border p-3 text-xs font-bold uppercase tracking-wider">Alert response records</header><div className="max-h-72 overflow-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="sticky top-0 bg-surface-secondary text-muted"><tr><th className="p-3">Alert</th><th className="p-3">Severity</th><th className="p-3">Status</th><th className="p-3">Violation</th><th className="p-3">Assigned</th><th className="p-3">Resolution</th></tr></thead><tbody className="divide-y divide-border">{snapshot.alerts.records.slice(0, 200).map((item) => <tr key={String(item.id)}><td className="p-3 text-primary">#{String(item.id)}</td><td className="p-3">{String(item.severity)}</td><td className="p-3">{String(item.status).replaceAll("_", " ")}</td><td className="p-3">{String(item.type).replaceAll("_", " ")}</td><td className="p-3">{String(item.assignedTo || "Unassigned")}</td><td className="max-w-64 p-3">{String(item.resolutionNote || item.falsePositiveReason || "Open")}</td></tr>)}</tbody></table></div></section>}
        </>}
      </>}</div></aside></div>;
}
