import { useMemo, useState } from "react";
import { CarFront, ChevronRight, Info } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { EmptyState } from "../../components/ui/States";
import { cx, titleCase } from "../../lib/format";
import type { AnalyticsData } from "../../types";

const colors = ["rgb(var(--color-primary))", "rgb(var(--color-info))", "rgb(var(--color-cyan))", "rgb(var(--color-danger))", "rgb(var(--color-purple))"];
const tooltipStyle = { background: "rgb(var(--color-surface))", border: "1px solid rgb(var(--color-border))", borderRadius: 12, color: "rgb(var(--color-ink))", boxShadow: "var(--shadow-card)", fontSize: 11 };

export function AnalyticsCharts({ data }: { data: AnalyticsData }) {
  const [interval, setInterval] = useState("30 min interval");
  const [selectedType, setSelectedType] = useState<string | null>(null);
  const total = useMemo(() => data.byType.reduce((sum, item) => sum + item.value, 0), [data.byType]);
  const leader = [...data.byType].sort((a, b) => b.value - a.value)[0];
  return (
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.05fr)_minmax(420px,.95fr)]">
      <section className="rounded-2xl border border-border bg-card p-4 shadow-panel">
        <header className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-sm font-bold">Detections over time <Info size={14} className="text-muted" /></h2><div className="mt-3 flex flex-wrap gap-2 text-[10px]"><span className="chart-legend"><span className="h-2 w-2 rounded-full bg-primary" />Total detections <strong>{data.timeline.reduce((sum, item) => sum + item.detections, 0).toLocaleString()}</strong></span><span className="chart-legend"><span className="h-2 w-2 rounded-full bg-danger" />Overspeed <strong>{data.timeline.reduce((sum, item) => sum + item.overspeed, 0).toLocaleString()}</strong></span></div></div><select value={interval} onChange={(event) => setInterval(event.target.value)} className="h-10 rounded-xl border border-border bg-surface px-3 text-[11px] text-ink"><option>30 min interval</option><option>Hourly interval</option></select></header>
        {data.timeline.length ? <div className="h-[330px]" role="img" aria-label="Bar chart of total and overspeed detections over time"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.timeline} margin={{ left: -16, right: 8, top: 8 }}><CartesianGrid stroke="rgb(var(--color-border))" strokeDasharray="3 4" vertical={false} /><XAxis dataKey="label" stroke="rgb(var(--color-muted))" tickLine={false} axisLine={false} fontSize={10} /><YAxis stroke="rgb(var(--color-muted))" tickLine={false} axisLine={false} fontSize={10} /><Tooltip contentStyle={tooltipStyle} cursor={{ fill: "rgb(var(--color-primary) / .06)" }} /><Legend wrapperStyle={{ fontSize: 10 }} /><Bar dataKey="detections" name="Total detections" fill="rgb(var(--color-primary))" radius={[5, 5, 0, 0]} maxBarSize={42} /><Bar dataKey="overspeed" name="Overspeed" fill="rgb(var(--color-danger))" radius={[5, 5, 0, 0]} maxBarSize={16} /></BarChart></ResponsiveContainer></div> : <EmptyState title="No detections in this period" message="Choose another time range or wait for new traffic events." />}
        {data.timeline.length > 0 && <div className="mt-2 flex items-center gap-3 rounded-xl border border-primary/15 bg-primary-soft px-4 py-3 text-xs"><span className="text-primary">↗</span><span className="flex-1">Peak activity at <strong>{[...data.timeline].sort((a, b) => b.detections - a.detections)[0]?.label}</strong> with <strong>{[...data.timeline].sort((a, b) => b.detections - a.detections)[0]?.detections.toLocaleString()}</strong> detections</span><ChevronRight size={15} className="text-primary" /></div>}
      </section>
      <section className="rounded-2xl border border-border bg-card p-4 shadow-panel">
        <header className="mb-3 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-sm font-bold">Vehicle distribution <Info size={14} className="text-muted" /></h2><span className="rounded-xl border border-border px-3 py-2 text-[10px] text-muted">By vehicle type</span></header>
        {data.byType.length ? <><div className="grid min-h-[330px] items-center gap-3 sm:grid-cols-[minmax(210px,.9fr)_minmax(200px,1.1fr)]"><div className="relative h-[250px]" role="img" aria-label={`Donut chart of ${total} vehicles by type`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.byType} dataKey="value" nameKey="name" innerRadius="58%" outerRadius="84%" paddingAngle={1} onClick={(item) => setSelectedType((current) => current === item.name ? null : item.name)}>{data.byType.map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]} opacity={!selectedType || selectedType === item.name ? 1 : .28} className="cursor-pointer outline-none transition-opacity" />)}</Pie><Tooltip contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><strong className="block text-2xl tabular-nums">{total.toLocaleString()}</strong><span className="text-[11px] text-muted">Total</span></div></div></div><div className="space-y-1">{data.byType.map((item, index) => { const percent = total ? item.value / total * 100 : 0; return <button type="button" key={item.name} onClick={() => setSelectedType((current) => current === item.name ? null : item.name)} className={cx("grid w-full grid-cols-[1fr_auto_auto] items-center gap-3 rounded-lg px-2 py-2 text-left text-xs hover:bg-elevated", selectedType === item.name && "bg-primary-soft")}><span className="flex items-center gap-2 font-semibold"><span className="h-2.5 w-2.5 rounded-full" style={{ background: colors[index % colors.length] }} />{titleCase(item.name)}</span><span className="tabular-nums text-muted">{percent.toFixed(1)}%</span><strong className="min-w-16 rounded-lg bg-primary-soft px-2 py-1 text-right tabular-nums text-primary">{item.value.toLocaleString()}</strong></button>})}</div></div>{leader && <div className="mt-2 flex items-center gap-3 rounded-xl border border-border bg-surface-secondary/60 px-4 py-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary-soft text-primary"><CarFront size={18} /></span><div className="flex-1"><p className="text-xs font-semibold">{titleCase(leader.name)} is the most detected vehicle type</p><p className="mt-0.5 text-[10px] text-muted">{total ? (leader.value / total * 100).toFixed(1) : 0}% of all detections</p></div><ChevronRight size={15} className="text-primary" /></div>}</> : <EmptyState title="No vehicle distribution" message="No classified vehicles were recorded in this period." />}
      </section>
    </div>
  );
}
